language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'

install: pip install -q -r requirements.txt

script: "cd tests/unit && py.test --cov-report=term --cov=space"

notifications:
  email:
      - david@makewhatis.com