language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'

before_install: 
  - pip install -q -r requirements.txt

script: 
   - python setup.py install

after_success:
  - coveralls

notifications:
  email:
      - david@makewhatis.com
