language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'

before_install: 
  - pip install -q -r requirements.txt

script: 
   - sed -i "s|module_dir.*|module_dir=$(pwd)/tests/unit/testmodules|g" tests/unit/test.ini
   - python setup.py test

after_success:
  - coveralls

notifications:
  email:
      - david@makewhatis.com
